---
# -- List of cluster administrators. These users will automatically get the role cluster-admin assigned.
# @default -- []
cluster_admin_list:
  - emergency

# -- Enable the settings and configuration of a project template.
# The information of the template can be found in templates/projecttempalte.yaml
# @default -- ''
projecttemplate:
  # -- Shall a project template be configured?
  # @default -- false
  enabled: false

  # -- Name of the project template
  # @default -- project-template
  name: project-template

# @ignore
generic-cluster-config:
  ############################
  # DISABLE SELF PROVISIONER #
  ############################
  self_provisioner:
    deactivate: true

  ######################
  # IDENTITY PROVIDERS #
  ######################
  idp:
    enabled: true
    # Define provider. Currently htpasswd and LDAP are supported
    providers:
      enabled: true
      htpasswd:
        - name: HTPASSWD
          enabled: true
          secretname: htpasswd-secret

  ##############
  # MONITORING #
  ##############
  monitoring:
    enabled: true
    enableUserWorkload: true

    ################
    # ALERTMANAGER #
    ################
    # Configuration for the cluster (main) Alertmanager
    alertmanagerMain:
      disable_local_alertmanager: false

      # Add storage to Alertmanager to keep the data.
      storage:
        class: gp3-csi
        size: 2Gi

    ##############
    # PROMETHEUS #
    ##############
    prometheusK8s:

      retention: 2d

      # Add storage to Prometheus to keep the data.
      storage:
        class: gp3-csi
        size: 10Gi
