---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: sonarqube
spec:
  encryptedData:
    adminpass: AgCl2XO4tc4qAfrjtNbECzvhC5d8WkyHaNGC3xo0ekaoMENkkv6aw2gtht44MZkRFg61+BhSksDuYlNQQ4+t3hpaa/mZruAlrgns54KDVrkiC/INSlfQlEyQ1KN22NM+Smnv+LdNYgj/x92EydTNdIGetYx3hNPWTHtAiFaYt7zfOaBmEFpTjyMsLuaTQGE3faDgWjf7E2yepKuhRnNPCiJI3IXuGg+7/mA0VnRlYmVKkzhubowq/8xIO+sx5a6tA39gT7cRI8e68c7rgAlUERYC5hyRlD7aV1pITnI8M0pEVTwclN2UqfLi4q5pjjTV2XZHZEE4tM6tkm+uZjU4YqpRAJqi2UEru4yYuzff7LJhdYU6AFN59TCQzoGLSq4SDxMrpak+a35/oWxGkAP17ts+dy4um7wzyCiyxkqNbQUK5i10ZMsUsy5r+zh8yjYvtVsk+8kTdMooyDraArJs5gnjRrZW2HS35n9Wa1cDXYgl9DKhc0EmqXFY8b3a4MoaJGDyIgDEk/N6k/BWF6Q10OQs1Pme3HqMM7eNpaIqbr7yPj1K2ugCGMRR6Df7JY//iTmmUjVsxZUvRdkIElMvvRDOJM2uLGawF3UVr3UoSk6br97MgW+cC1ahB14qpcLbfg+L8M+q+gdtj1kIlk+Qy/wxi1nrjhNx1QMSPJOP7ZYubuHZt5aQ0r0UQ4ShlkVTMj4Rmqe2dS2SRYo=
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: sonarqube
